---
title       : Flow Rate Calculator 
subtitle    : Flow in a canal and force on a sluice gate
author      : YonasTH
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [quiz, mathjax]      # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides

--- .class #id   

## What does the calculator do?
- Estimates flow of water in a canal which has a sluice gate to control flow    
- It also computes force of the water on the gate  
- Input required are the width of the canal and upstream and downstream depth of water  

--- .class #id 

## Basic Formulation  
Bernoulli's equation and momentum equations are used to estimate flow and force.
$$flow rate = \frac{b y_{1}\sqrt{2gy_{2}}}{\sqrt{\frac{y_{1}}{y_{2}}+1}}$$  
$$force = \rho b(V_{2}^2y_{2} - V_{1}^2y_{1}) - \rho gb\frac{y_{1}^2 -y_{2}^2}{2}$$
where $V_{1}$ and $V_{2}$ are upstream and downstream flow velocities given by $V_{1}= b y_{1}$ and $V_{2}= b y_{2}$, respectively  

--- .class #id   

## Sample Calculation and plot 
```{r echo=FALSE, cache=FALSE, results='asis'}
library(shiny)
library(ggplot2)
g <- 9.81
rho <- 1000
flowRate <- function(b, y1, y2) b*y1*sqrt(2*g*y2)/sqrt((y1/y2)+1)
force <- function(b, y1, y2){
  v1 <- b*y1
  v2 <- b*y2
  f <- rho*b*(v2^2*y2-v1^2*y1)-rho*g*b/2*(y1^2-y2^2)
  -1*f/1e5
}
plt <- function(y1, y2) {
  data <- data.frame(x1=c(0,4),x2=c(4.5,8.5), Y1=c(y1,y1), Y2=c(y2, y2))
  ymin <- data.frame(ymin=y2, ymax=5, xmax=4.5, xmin=4, y1=y1)
  q <- ggplot()+geom_line(data=data, aes(x1, Y1), col="blue")+
    geom_line(data=data, aes(x2, Y2), col="blue")+xlab("x")+ylab("y")+
    geom_rect(data=ymin, aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), fill="brown", col ="black")+
    geom_rect(data=ymin, aes(xmin=0, xmax=8.5, ymin=0, ymax=0.25), fill="grey")
  q+coord_cartesian(xlim=c(0,8.5), ylim=c(0,5))+
    annotate("text", x=1, y=ymin$y1+0.25, label = "Y1")+
    annotate("text", x=7.5, y=ymin$ymin+0.25, label = "Y2")+
    annotate("text", x=4.75, y=(ymin$ymin+5)/2, label = "Gate")
}
plt(4,2)
```

--- .class #id  

## Documentation  
### Inputs and Outputs  
Flow Rate calcualtor calculates volume of water flowing through a canal. It uses Bernoulli's equation to estimate flow underneath a sluice gate in a canal from measurements of water depth upstream and downstream of the gate. Additionaly, force exerted on the gate is calculated from the water depths.  

### Input Variables  
b = canal width  
y1 = upstream water depth  
y2 = downstream water depth  

### Notes   
- The calculator is limited to a canal with dimensions 5m x 5m x 5m. Therefore, the depths and width input can not exceed 5m.